plugins {
    id 'com.android.library'
}

android {
    namespace 'com.github.kiulian.downloader'

    compileSdk 36

    defaultConfig {
        minSdk 23
        targetSdk 28
    }
}

dependencies {
    implementation 'com.google.code.gson:gson:' + gsonVersion
    implementation 'com.squareup.okhttp3:okhttp:' + okhttpVersion
}